import {
  AdjustmentsHorizontalIcon,
  ArchiveBoxArrowDownIcon,
  ArchiveBoxIcon,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ChevronLeftIcon,
  ArrowRightIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowTurnDownRightIcon,
  AtSymbolIcon,
  BanknotesIcon,
  BeakerIcon,
  BellIcon,
  BuildingOffice2Icon,
  BuildingStorefrontIcon,
  CalculatorIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  CircleStackIcon,
  ClockIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentListIcon,
  Cog6ToothIcon,
  CubeIcon,
  CurrencyDollarIcon,
  DocumentPlusIcon,
  DocumentDuplicateIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FolderIcon,
  HandRaisedIcon,
  HashtagIcon,
  HomeModernIcon,
  IdentificationIcon,
  InboxStackIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  PencilSquareIcon,
  PhoneIcon,
  PlusIcon,
  PuzzlePieceIcon,
  QueueListIcon,
  RectangleStackIcon,
  ScaleIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SparklesIcon,
  Squares2X2Icon,
  SwatchIcon,
  TagIcon,
  TicketIcon,
  TruckIcon,
  UserGroupIcon,
  UsersIcon,
  VariableIcon,
  XMarkIcon,
  ForwardIcon,
} from "@heroicons/react/24/outline";
import {
  CheckIcon,
  CheckCircleIcon,
  ExclamationCircleIcon,
  InformationCircleIcon,
  XMarkIcon as XMarkSolidIcon,
} from "@heroicons/react/20/solid";

const ICONS = {
  "hero-adjustments-horizontal": AdjustmentsHorizontalIcon,
  "hero-archive-box": ArchiveBoxIcon,
  "hero-archive-box-arrow-down": ArchiveBoxArrowDownIcon,
  "hero-arrow-down-tray": ArrowDownTrayIcon,
  "hero-arrow-left": ArrowLeftIcon,
  "hero-chevron-left": ChevronLeftIcon,
  "hero-arrow-right": ArrowRightIcon,
  "hero-arrow-right-start-on-rectangle": ArrowRightStartOnRectangleIcon,
  "hero-arrow-turn-down-right": ArrowTurnDownRightIcon,
  "hero-at-symbol": AtSymbolIcon,
  "hero-banknotes": BanknotesIcon,
  "hero-beaker": BeakerIcon,
  "hero-bell": BellIcon,
  "hero-building-office-2": BuildingOffice2Icon,
  "hero-building-storefront": BuildingStorefrontIcon,
  "hero-calculator": CalculatorIcon,
  "hero-calendar-days": CalendarDaysIcon,
  "hero-chart-bar": ChartBarIcon,
  "hero-chart-pie": ChartPieIcon,
  "hero-chevron-down": ChevronDownIcon,
  "hero-chevron-right": ChevronRightIcon,
  "hero-circle-stack": CircleStackIcon,
  "hero-clock": ClockIcon,
  "hero-clipboard-document-check": ClipboardDocumentCheckIcon,
  "hero-clipboard-document-list": ClipboardDocumentListIcon,
  "hero-cog-6-tooth": Cog6ToothIcon,
  "hero-cube": CubeIcon,
  "hero-currency-dollar": CurrencyDollarIcon,
  "hero-document-plus": DocumentPlusIcon,
  "hero-document-duplicate": DocumentDuplicateIcon,
  "hero-document-text": DocumentTextIcon,
  "hero-exclamation-triangle": ExclamationTriangleIcon,
  "hero-eye": EyeIcon,
  "hero-eye-slash": EyeSlashIcon,
  "hero-folder": FolderIcon,
  "hero-hand-raised": HandRaisedIcon,
  "hero-hashtag": HashtagIcon,
  "hero-home-modern": HomeModernIcon,
  "hero-identification": IdentificationIcon,
  "hero-inbox-stack": InboxStackIcon,
  "hero-lock-closed": LockClosedIcon,
  "hero-magnifying-glass": MagnifyingGlassIcon,
  "hero-map-pin": MapPinIcon,
  "hero-pencil-square": PencilSquareIcon,
  "hero-phone": PhoneIcon,
  "hero-plus": PlusIcon,
  "hero-puzzle-piece": PuzzlePieceIcon,
  "hero-queue-list": QueueListIcon,
  "hero-rectangle-stack": RectangleStackIcon,
  "hero-scale": ScaleIcon,
  "hero-shield-check": ShieldCheckIcon,
  "hero-shopping-bag": ShoppingBagIcon,
  "hero-shopping-cart": ShoppingCartIcon,
  "hero-sparkles": SparklesIcon,
  "hero-squares-2x2": Squares2X2Icon,
  "hero-swatch": SwatchIcon,
  "hero-tag": TagIcon,
  "hero-ticket": TicketIcon,
  "hero-truck": TruckIcon,
  "hero-user-group": UserGroupIcon,
  "hero-users": UsersIcon,
  "hero-variable": VariableIcon,
  "hero-x-mark": XMarkIcon,
  "hero-check": CheckIcon,
  "hero-x-mark-solid": XMarkSolidIcon,
  "hero-information-circle-mini": InformationCircleIcon,
  "hero-check-circle-mini": CheckCircleIcon,
  "hero-exclamation-circle-mini": ExclamationCircleIcon,
  "hero-forward": ForwardIcon,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className,
}: {
  name: IconName | string;
  className?: string;
}) {
  const Cmp = ICONS[name as IconName];
  if (!Cmp) return null;
  return <Cmp className={className} aria-hidden="true" />;
}
