import {
  AdjustmentsHorizontalIcon,
  ArchiveBoxIcon,
  ArrowDownTrayIcon,
  ArrowRightIcon,
  ArrowRightStartOnRectangleIcon,
  AtSymbolIcon,
  BanknotesIcon,
  BeakerIcon,
  BuildingOffice2Icon,
  BuildingStorefrontIcon,
  CalculatorIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChevronDownIcon,
  ClipboardDocumentListIcon,
  Cog6ToothIcon,
  CubeIcon,
  CurrencyDollarIcon,
  DocumentTextIcon,
  EyeIcon,
  EyeSlashIcon,
  HandRaisedIcon,
  HashtagIcon,
  IdentificationIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  PencilSquareIcon,
  PhoneIcon,
  PlusIcon,
  ShieldCheckIcon,
  ShoppingCartIcon,
  Squares2X2Icon,
  TagIcon,
  TicketIcon,
  UserGroupIcon,
  UsersIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import {
  CheckIcon,
  CheckCircleIcon,
  ExclamationCircleIcon,
  InformationCircleIcon,
  XMarkIcon as XMarkSolidIcon,
} from "@heroicons/react/20/solid";

const ICONS = {
  "hero-adjustments-horizontal": AdjustmentsHorizontalIcon,
  "hero-archive-box": ArchiveBoxIcon,
  "hero-arrow-down-tray": ArrowDownTrayIcon,
  "hero-arrow-right": ArrowRightIcon,
  "hero-arrow-right-start-on-rectangle": ArrowRightStartOnRectangleIcon,
  "hero-at-symbol": AtSymbolIcon,
  "hero-banknotes": BanknotesIcon,
  "hero-beaker": BeakerIcon,
  "hero-building-office-2": BuildingOffice2Icon,
  "hero-building-storefront": BuildingStorefrontIcon,
  "hero-calculator": CalculatorIcon,
  "hero-calendar-days": CalendarDaysIcon,
  "hero-chart-bar": ChartBarIcon,
  "hero-chart-pie": ChartPieIcon,
  "hero-chevron-down": ChevronDownIcon,
  "hero-clipboard-document-list": ClipboardDocumentListIcon,
  "hero-cog-6-tooth": Cog6ToothIcon,
  "hero-cube": CubeIcon,
  "hero-currency-dollar": CurrencyDollarIcon,
  "hero-document-text": DocumentTextIcon,
  "hero-eye": EyeIcon,
  "hero-eye-slash": EyeSlashIcon,
  "hero-hand-raised": HandRaisedIcon,
  "hero-hashtag": HashtagIcon,
  "hero-identification": IdentificationIcon,
  "hero-lock-closed": LockClosedIcon,
  "hero-magnifying-glass": MagnifyingGlassIcon,
  "hero-map-pin": MapPinIcon,
  "hero-pencil-square": PencilSquareIcon,
  "hero-phone": PhoneIcon,
  "hero-plus": PlusIcon,
  "hero-shield-check": ShieldCheckIcon,
  "hero-shopping-cart": ShoppingCartIcon,
  "hero-squares-2x2": Squares2X2Icon,
  "hero-tag": TagIcon,
  "hero-ticket": TicketIcon,
  "hero-user-group": UserGroupIcon,
  "hero-users": UsersIcon,
  "hero-x-mark": XMarkIcon,
  "hero-check": CheckIcon,
  "hero-x-mark-solid": XMarkSolidIcon,
  "hero-information-circle-mini": InformationCircleIcon,
  "hero-check-circle-mini": CheckCircleIcon,
  "hero-exclamation-circle-mini": ExclamationCircleIcon,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className,
}: {
  name: IconName | string;
  className?: string;
}) {
  const Cmp = ICONS[name as IconName];
  if (!Cmp) return null;
  return <Cmp className={className} aria-hidden="true" />;
}
